---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-iam-authenticator-proxy.fullname" . }}
  labels:
{{ include "aws-iam-authenticator-proxy.labels" . | indent 4 }}
stringData:
  aws_access_key_id: {{ .Values.aws.access_key_id | quote }}
  aws_secret_access_key: {{ .Values.aws.secret_access_key | quote }}
  psk: {{ .Values.psk | quote }}
