{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "aws-iam-authenticator-proxy.serviceAccountName" . }}
  labels:
{{ include "aws-iam-authenticator-proxy.labels" . | indent 4 }}
{{- end -}}
